### ISSUE TITLE
fofa查询还支持吗

### ISSUE THREAD

**Issue by LuoooB** [i11us0ry/goon#1]
昨天看师傅删了，说不支持了 。今天的readme上面还有key选项  。。enmmm到底删了没

**Comment by i11us0ry** [comment]
正常模式可以查询的哦，删除的是不限数量的功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 晚上11:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] fofa查询还支持吗 (#1)




 
昨天看师傅删了，说不支持了 。今天的readme上面还有key选项  。。enmmm到底删了没
