### ISSUE TITLE
能增加代理功能吗？

### ISSUE THREAD

**Issue by kevinbbjj** [i11us0ry/goon#10]
能增加代理功能吗？如--proxy参数等，有http/https,socks5代理。谢谢

**Comment by i11us0ry** [comment]
这个用proxifier就好了呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月2日(周四) 上午9:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] 能增加代理功能吗？ (Issue #10)




 
能增加代理功能吗？如--proxy参数等，有http/https,socks5代理。谢谢
