### ISSUE TITLE
部分URL无法获取标题及输出建议

### ISSUE THREAD

**Issue by Alexander4731** [i11us0ry/goon#12]
一、无法获取标题的URL（应该是两次跳转）

> http://face.zufe.edu.cn
> http://achat.zjff.edu.cn

二、http和https标题不同的情况能否共存，因为有些情况下只有子域名。
> http://achat.zjff.edu.cn（“智慧纺服”）
> https://achat.zjff.edu.cn（“系统提示”）

三、输出结果的建议。

1. 输出结果为乱序，最好和源文本保持一致。
2. 不能访问的URL可否在结果中标识而不是直接丢弃（例如“无法访问”、“响应超时”）
3. 同时输出状态码和解析的IP（200/302/400/502，解析结果ip+端口）
4. 能否加一栏显示跳转的网页（因为部分网站跳转之后带URL路径，而且也是要对跳转之后的网页进行测试）

已给Star+土司打赏评分

**Comment by i11us0ry** [comment]
感谢提交，会尽快和新功能一起更新



---原始邮件---
发件人: "ζั͡ޓއއއ ***@***.***&gt;
发送时间: 2022年8月17日(周三) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] 部分URL无法获取标题及输出建议 (Issue #12)




 
一、无法获取标题的URL（应该是两次跳转）
  
http://face.zufe.edu.cn
 http://achat.zjff.edu.cn
  
二、http和https标题不同的情况能否共存，因为有些情况下只有子域名。
  
http://achat.zjff.edu.cn（“智慧纺服”）
 https://achat.zjff.edu.cn（“系统提示”）
  
三、输出结果的建议。
  
输出结果为乱序，最好和源文本保持一致。 

不能访问的URL可否在结果中标识而不是直接丢弃（例如“无法访问”、“响应超时”） 

同时输出状态码和解析的IP（200/302/400/502，解析结果ip+端口） 

能否加一栏显示跳转的网页（因为部分网站跳转之后带URL路径，而且也是要对跳转之后的网页进行测试） 
 
已给Star+土司打赏评分

**Comment by i11us0ry** [comment]
关于以上三个例子无法获取准确title，是因为他们的跳转都是采用js跳转的，且跳转方法是重命名和重定义的，因此在没有无头浏览器的情况下考脚本几乎无法获取到。跳转如下：
(function () {
	var loc = window.location;
	var url = loc.protocol+"//"+loc.host;
	if(/\/$/g.test(url)){
		url = url.substring(0,url.length-1);
	}
	url = encodeURIComponent(url);
	//注意: 以下注释中的代码不可修改和重复, 客户端要从中解析地址
	/* 
		if(CookiesEnabled())
		g_lines = [{src:"",url:"https://achat.zjff.edu.cn/por/?entry_id=2",flag:'win_location("https://achat.zjff.edu.cn/por/?entry_id=2")',right:0}];
	*/
	g_lines = [{src:"",url:"https://achat.zjff.edu.cn/public/cas_login?entry_id=2",right:0}];
	gotoLines();
}

**Comment by Alexander4731** [comment]
我在想能不能把类似的关键字提取出来，比如“.location”这样，然后再标识出来，毕竟这些网页确实占少数，可以自己写爬虫。
然后这几天在用的时候发现默认线程数500太高，家里300M的网络可访问率仅为6%，调成20线程就可以达到80%以上。
最后最后，期待项目的更新以及对输出结果的优化。🙌
