### ISSUE TITLE
在哪配置fofa的email和key

### ISSUE THREAD

**Issue by hiyoshiy** [i11us0ry/goon#16]

**Comment by i11us0ry** [comment]
配置文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月9日(周一) 中午12:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] 在哪配置fofa的email和key (Issue #16)

**Comment by G1019743666** [comment]
在check目录下的conf.go文件中50行配置，配置后需要重新编译才行

**Comment by i11us0ry** [comment]
不是啊大哥 congrats.yml里配置啊。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月24日(周五) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [i11us0ry/goon] 在哪配置fofa的email和key (Issue #16)




 
在check目录下的conf.go文件中50行配置，配置后需要重新编译才行

**Comment by i11us0ry** [comment]
不是啊大哥 conf.yml里配置啊。。。

illusory
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "i11us0ry/goon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [i11us0ry/goon] 在哪配置fofa的email和key (Issue #16)





 
在check目录下的conf.go文件中50行配置，配置后需要重新编译才行
