### ISSUE TITLE
我爆破的时候能扫到服务，爆破不出来结果，大佬指导一下！

### ISSUE THREAD

**Issue by bytzboy** [i11us0ry/goon#17]
![telnet](https://user-images.githubusercontent.com/63386943/233813267-9c140240-2acd-4204-83b9-e1ff3dfad374.png)

**Comment by i11us0ry** [comment]
telnet爆破只是个半成品，每个系统开的telnet、每家厂商的telnet协议头都不一样，很难做到统一，我这个也只是针对windows下和linux下的某些telnet，并不能针对所有telnet

**Comment by bytzboy** [comment]
大佬好，我这个好像所有的爆破功能都没启动，都没运行，请大佬指点一下没那个telnet的也是windows的。
![image](https://user-images.githubusercontent.com/63386943/233816223-15f1b1dd-44ab-4ddd-8a1e-88ea6f4ccda6.png)

**Comment by i11us0ry** [comment]
运行记录发一下，ip打码就行了

**Comment by bytzboy** [comment]
我这边好像只运行扫描任务，不运行破解程序。
![666](https://user-images.githubusercontent.com/63386943/233816411-e9c65fd2-b440-426c-b086-63ab829d4616.png)
![777](https://user-images.githubusercontent.com/63386943/233816416-5c35c66a-d4b3-472e-a537-5621a7ec7644.png)

**Comment by i11us0ry** [comment]
emmm  我还以为是你自己搭的环境，当出现start xxx brute的时候就是已经启动爆破了，只是只显示爆破成功数据，不会显示爆破过程，你这样的都是爆破失败的呀

**Comment by i11us0ry** [comment]
你可以导一些国外的ssh、rdp、mysql资产啥的跑一下就知道了

**Comment by i11us0ry** [comment]
或者自己搭几个服务

**Comment by bytzboy** [comment]
哦哦，明白了。。。。
