### ISSUE TITLE
你好，请问我如果fofa查询想要app="" && ""应该如何查询呢

### ISSUE THREAD

**Issue by apsry** [i11us0ry/goon#2]

**Comment by i11us0ry** [comment]
放到文件如key.txt中，然后用ifile就行啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月18日(周日) 晚上8:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [i11us0ry/goon] 你好，请问我如果fofa查询想要app="" &amp;&amp; ""应该如何查询呢 (#2)
