### ISSUE TITLE
mac 平台不知道为什么获取不到参数呢，自己编译也是一样

### ISSUE THREAD

**Issue by umbll** [i11us0ry/goon#20]
![CleanShot 2024-03-08 at 16 36 24](https://github.com/i11us0ry/goon/assets/130435305/c80cb14b-2ad9-4cf3-920c-20f75a523106)
![CleanShot 2024-03-08 at 16 41 54](https://github.com/i11us0ry/goon/assets/130435305/f1428e2e-8bde-4911-b8dd-e53803501f1b)

**Comment by i11us0ry** [comment]
sudo试下
