### ISSUE TITLE
mac下无法扫描，win下正常

### ISSUE THREAD

**Issue by chenchenhen6** [i11us0ry/goon#5]
![image](https://user-images.githubusercontent.com/35289748/146716634-c178da3f-d834-4b86-9b7e-55ffec98f463.png)
mac下icmp不到存活的ip，但是我在win下就可以，麻烦师傅看看什么情况
![image](https://user-images.githubusercontent.com/35289748/146716738-93465042-d4c6-4965-9505-4576da46ecc9.png)

**Comment by i11us0ry** [comment]
> ![image](https://user-images.githubusercontent.com/35289748/146716634-c178da3f-d834-4b86-9b7e-55ffec98f463.png) mac下icmp不到存活的ip，但是我在win下就可以，麻烦师傅看看什么情况 ![image](https://user-images.githubusercontent.com/35289748/146716738-93465042-d4c6-4965-9505-4576da46ecc9.png)

试试sudo权限

**Comment by chenchenhen6** [comment]
解决了，感谢师傅
